
'use server';

import catalystService from '@/services/catalyst';
import type {
  GenerateBudgetReportInput,
  GenerateBudgetReportOutput,
} from '@/ai/schemas/budget-report';
import { GenerateBudgetReportOutputSchema } from '@/ai/schemas/budget-report';

function parseCurrency(amount: string | number): number {
  if (typeof amount === 'number') {
    return amount;
  }
  if (typeof amount === 'string') {
    const sanitizedAmount = amount.replace(/[^0-9.-]+/g, '');
    const parsed = parseFloat(sanitizedAmount);
    return isNaN(parsed) ? 0 : parsed;
  }
  return 0;
}

export async function generateBudgetReport(
  input: GenerateBudgetReportInput
): Promise<GenerateBudgetReportOutput> {
  const transactionsList = input.transactions
    .map(t => `- ${t.description}: ${t.amount} (${t.type}) on ${t.date}`)
    .join('\n');

  const systemPrompt = `You are a financial analyst. Your response MUST be ONLY a valid JSON object that conforms to the output schema. Do NOT include any other text, markdown, or explanations.`;
  
  const userPrompt = `Based on the following transactions, provide a detailed spending analysis and an expense breakdown.
Group similar expenses into logical categories (e.g., "Food & Dining", "Transport", "Shopping", "Bills & Utilities", "Entertainment").

Your response must be a JSON object that conforms exactly to this schema:
{
  "summary": "(string) An AI-generated summary and analysis of spending habits, formatted as an HTML unordered list (<ul><li>...</li></ul>). Each list item should highlight a key trend or provide an actionable piece of advice.",
  "expenseBreakdown": [
    { "name": "(string) CategoryName", "value": "(number) 1234.56" },
    ...
  ]
}

Here is the list of transactions to analyze:
${transactionsList}
`;

  try {
    const responseText = await catalystService.generateText(userPrompt, systemPrompt);
    // Simple cleaning for JSON response
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("AI did not return a valid JSON object.");
    }
    const cleanedText = jsonMatch[0];
    const parsed = JSON.parse(cleanedText);

    // Manually calculate overall breakdown
    let totalIncome = 0;
    let totalExpenses = 0;
    input.transactions.forEach(t => {
        const amount = parseCurrency(t.amount);
        if (t.type === 'income') {
            totalIncome += amount;
        } else {
            totalExpenses += amount;
        }
    });

    const savings = Math.max(0, totalIncome - totalExpenses);
    const savingsRate = totalIncome > 0 ? Math.round((savings / totalIncome) * 100) : 0;

    // We add the 'overallBreakdown' after parsing because it's calculated, not generated by the AI
    parsed.overallBreakdown = {
        totalIncome,
        totalExpenses,
        savings,
        savingsRate
    };

    return GenerateBudgetReportOutputSchema.parse(parsed);
    
  } catch (e: any) {
    console.error('Failed to parse JSON from model response:', e.message);
    throw new Error('Could not generate budget report. The AI returned an invalid format.');
  }
}
